version: 2

project_name: clippy

before:
  hooks:
    - go mod tidy

builds:
  - id: clippy-darwin
    main: ./cmd/clippy
    binary: clippy
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: clippy-windows
    main: ./cmd/clippy
    binary: clippy
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: pasty-darwin
    main: ./cmd/pasty
    binary: pasty
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: pasty-windows
    main: ./cmd/pasty
    binary: pasty
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: neilberkman
    name: clippy
  draft: false
  prerelease: auto
  make_latest: true
  mode: replace
  header: |
    ## Clippy {{.Tag}} - Unified Clipboard Tool for macOS & Windows

    A smart clipboard utility that intelligently handles both text and file copying based on content type.

    ### 🎯 Features
    - Automatic content type detection
    - Smart file path expansion
    - Multiple file support
    - Natural language file copying (e.g., "copy *.txt")
    - Integration with system clipboard
    - Cross-platform support (macOS & Windows)

    ### 📦 Installation
    
    #### macOS - Homebrew (Recommended)
    ```bash
    brew tap neilberkman/clippy
    brew install clippy  # Installs both clippy and pasty
    ```
    
    #### Windows - Scoop (Recommended)
    ```powershell
    scoop bucket add clippy https://github.com/neilberkman/scoop-clippy
    scoop install clippy  # Installs both clippy and pasty
    ```
    
    #### Direct Download
    ```bash
    # macOS - Apple Silicon (M1/M2):
    curl -L https://github.com/neilberkman/clippy/releases/download/{{.Tag}}/clippy_{{.Tag}}_darwin_arm64.tar.gz | tar xz

    # macOS - Intel:
    curl -L https://github.com/neilberkman/clippy/releases/download/{{.Tag}}/clippy_{{.Tag}}_darwin_amd64.tar.gz | tar xz
    
    # Windows:
    # Download clippy_{{.Tag}}_windows_amd64.zip and extract to your PATH
    ```

  footer: |
    **Full Changelog**: https://github.com/neilberkman/clippy/compare/{{.PreviousTag}}...{{.Tag}}
    
    ---
    🐛 **Found a bug?** Please [open an issue](https://github.com/neilberkman/clippy/issues/new)

brews:
  - repository:
      owner: neilberkman
      name: homebrew-clippy
    directory: Formula
    homepage: "https://github.com/neilberkman/clippy"
    description: "Unified clipboard tool for macOS - a superset of pbcopy"
    license: "MIT"
    test: |
      system "#{bin}/clippy", "--version"
    install: |
      bin.install "clippy"
      bin.install "pasty"

scoops:
  - repository:
      owner: neilberkman
      name: scoop-clippy
    directory: bucket
    homepage: "https://github.com/neilberkman/clippy"
    description: "Unified clipboard tool for Windows - a superset of clip"
    license: "MIT"