version: 2

project_name: clippy

before:
  hooks:
    - go mod tidy

builds:
  - id: clippy
    main: ./cmd/clippy
    binary: clippy
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/neilberkman/clippy/cmd/internal/common.Version={{.Version}} -X github.com/neilberkman/clippy/cmd/internal/common.Commit={{.Commit}} -X github.com/neilberkman/clippy/cmd/internal/common.Date={{.Date}}
  - id: pasty
    main: ./cmd/pasty
    binary: pasty
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/neilberkman/clippy/cmd/internal/common.Version={{.Version}} -X github.com/neilberkman/clippy/cmd/internal/common.Commit={{.Commit}} -X github.com/neilberkman/clippy/cmd/internal/common.Date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: clippy
  draft: false
  prerelease: auto
  make_latest: true
  mode: replace
  header: |
    ## Clippy {{.Tag}} - Unified Clipboard Tool for macOS

    A smart clipboard utility that intelligently handles both text and file copying based on content type.

    ### 🎯 Features
    - Automatic content type detection
    - Smart file path expansion
    - Multiple file support
    - Natural language file copying (e.g., "copy *.txt")
    - Integration with system clipboard

    ### 📦 Installation

    #### Homebrew (Recommended)
    ```bash
    brew install clippy  # Installs both clippy and pasty
    ```

    #### Direct Download
    ```bash
    # For Apple Silicon (M1/M2):
    curl -L https://github.com/neilberkman/clippy/releases/download/{{.Tag}}/clippy_{{.Tag}}_darwin_arm64.tar.gz | tar xz

    # For Intel Macs:
    curl -L https://github.com/neilberkman/clippy/releases/download/{{.Tag}}/clippy_{{.Tag}}_darwin_amd64.tar.gz | tar xz

    # Move to your PATH
    sudo mv clippy /usr/local/bin/
    ```

  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/clippy/compare/{{.PreviousTag}}...{{.Tag}}

    ---
    🐛 **Found a bug?** Please [open an issue](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/clippy/issues/new)

# brews section removed - clippy is now in Homebrew Core
# The tap (neilberkman/clippy) is kept only for Draggy cask
# Users should install clippy with: brew install clippy
